In [38]:
import torch
import numpy as np

In [15]:
torch.empty(2, 2, 2, 3)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

In [16]:
torch.rand(2, 2)

tensor([[0.7396, 0.8760],
        [0.2334, 0.3913]])

In [17]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [20]:
x = torch.ones(2, 2, dtype=torch.int)

In [21]:
print(x.dtype)

torch.int32


In [22]:
x.size()

torch.Size([2, 2])

In [14]:
torch.zeros(1)

tensor([0.])

In [25]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
y.add_(x)
print(y)

tensor([[1.3845, 0.7531],
        [1.2587, 1.6315]])


In [27]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3218, 0.5897, 0.4427],
        [0.9804, 0.6786, 0.6629],
        [0.2115, 0.0310, 0.1585],
        [0.2775, 0.5980, 0.1255],
        [0.9960, 0.3074, 0.8709]])


In [28]:
print(x[:, 0])

tensor([0.3218, 0.9804, 0.2115, 0.2775, 0.9960])


In [29]:
print(x[1, 1])

tensor(0.6786)


In [30]:
print(x[1, 1].item())

0.6786426305770874


In [32]:
x = torch.rand(4, 4)
print(x)

tensor([[0.3759, 0.2270, 0.3309, 0.9285],
        [0.6226, 0.0660, 0.3529, 0.5146],
        [0.7843, 0.8555, 0.4120, 0.2371],
        [0.8945, 0.2791, 0.1293, 0.4271]])


In [33]:
y = x.view(16)
print(y)

tensor([0.3759, 0.2270, 0.3309, 0.9285, 0.6226, 0.0660, 0.3529, 0.5146, 0.7843,
        0.8555, 0.4120, 0.2371, 0.8945, 0.2791, 0.1293, 0.4271])


In [37]:
y = x.view(-1, 8)
print(y.size())

torch.Size([2, 8])


In [39]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [40]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
