In [1]:
import torch

In [18]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.9671, -1.6449, -0.4425], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([1.1979, 3.2770, 3.2886], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
# z = z.mean()
print(z)

tensor([ 2.8697, 21.4769, 21.6303], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([ 2.0763, 17.4771,  4.3980])


In [14]:
x.requires_grad_(False)
print(x)

tensor([-0.8021,  1.2770,  1.2886])


In [19]:
y = x.detach()
print(y)

tensor([-0.9671, -1.6449, -0.4425])


In [21]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.0329, 0.3551, 1.5575])


In [33]:
weights = torch.ones(4, requires_grad=True)

In [29]:
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
